import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";

const sora = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body
                    className={`${sora.className} min-h-screen flex flex-col`}
                >
                    <Navbar />
                    <div className="flex-1 w-full">
                        <div className="max-w-6xl mx-auto">{children}</div>
                    </div>
                </body>
            </html>
        </ClerkProvider>
    );
}
